[mongodb]
mongodb.daws90s.com ansible_user=ec2-user ansible_password=DevOps321

[catalogue]
catalogue.daws90s.com

[redis]
redis.daws90s.com

[user]
user.daws90s.com

[cart]
cart.daws90s.com

[frontend]
frontend.daws90s.com

[mysql]
mysql.daws90s.com

[shipping]
shipping.daws90s.com

[rabbitmq.yaml]
rabbitmq.daws90s.com





